//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Troy.TSPE3.Licensing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Troy.TSPE3.Licensing.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {646B7873-11BD-4CDB-8DE3-4B96D0752453}.
        /// </summary>
        public static string ApplicationId {
            get {
                return ResourceManager.GetString("ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to license.
        /// </summary>
        public static string LicenseFileName {
            get {
                return ResourceManager.GetString("LicenseFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lwKAAAEAAAByUHjfAHLQAVoANAFBcHBJRD17NjQ2Qjc4NzMtMTFCRC00Q0RCLThERTMtNEI5NkQwNzUyNDUzfSNDb21wYW55TmFtZT10cmlhbCNDdXN0b21lcklEPXRyaWFsI0Rlc3RpbmF0aW9uRGV2aWNlcz0xI1NvdXJjZURldmljZXM9MSNDb250YWN0RW1haWw9dHJpYWxAdHJpYWwuY29tI0N1c3RvbWVyU2VyaWFsTnVtYmVyPSNDb250YWN0TmFtZT0jQ29udGFjdFBob25lPSNTYWxlc09yZGVyTnVtYmVyPSNUcm95U3VwcG9ydEVtYWlsPXN1cHBvcnRAdHJveWdyb3VwLmNvbSNUcm95U3VwcG9ydFBob25lPTEtODU1LTg4OS0xMTA5I1VubGltaXRlZD1ubyNEb21haW5Db2RlPQEBTAMfb8I+gCqN6HUbINL3nY5328TWixF5QBoWy/9VrMMnYIjRNd8PDjAyBVoF4cRB.
        /// </summary>
        public static string TrialCode {
            get {
                return ResourceManager.GetString("TrialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMAAMACAaUsVHU4sX/M2lBq2MVAA221+t9Lze5nXXgCxhOlJ7yB7Ev+NvJxKK2JvKE1/AqMDAAEAAQ==.
        /// </summary>
        public static string ValidationKey {
            get {
                return ResourceManager.GetString("ValidationKey", resourceCulture);
            }
        }
    }
}
